// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $infoPelicula_name_ from "./routes/infoPelicula/[name].tsx";
import * as $proyectos from "./routes/proyectos.tsx";
import * as $AddPelicula from "./islands/AddPelicula.tsx";
import * as $EliminarPelicula from "./islands/EliminarPelicula.tsx";
import * as $EliminarProyecto from "./islands/EliminarProyecto.tsx";
import * as $Modal from "./islands/Modal.tsx";
import * as $filtrado from "./islands/filtrado.tsx";
import * as $galletas from "./islands/galletas.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
    "./routes/infoPelicula/[name].tsx": $infoPelicula_name_,
    "./routes/proyectos.tsx": $proyectos,
  },
  islands: {
    "./islands/AddPelicula.tsx": $AddPelicula,
    "./islands/EliminarPelicula.tsx": $EliminarPelicula,
    "./islands/EliminarProyecto.tsx": $EliminarProyecto,
    "./islands/Modal.tsx": $Modal,
    "./islands/filtrado.tsx": $filtrado,
    "./islands/galletas.tsx": $galletas,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
